### recuperar todos los usuarios
GET http://localhost:3000/users
### crear un usuario
POST http://localhost:3000/users
Content-type: application/json

{
    "username": "Edu",
    "password": "12345",
    "email": "edu@gmail.com"
}


### recuperar las plantas
GET http://localhost:3000/plants/

### crear plantas
POST http://localhost:3000/plants
Content-Type: multipart/form-data; boundary=FormBoundary12345

--FormBoundary12345
Content-Disposition: form-data; name="commonName"

Cactus de Navidad
--FormBoundary12345
Content-Disposition: form-data; name="image"; filename="aloe-vera.jpg"
Content-Type: image/jpeg

< ../public/aloe-vera.jpg
--FormBoundary12345--

### recuperar las plantas por nombre
GET http://localhost:3000/plants/external?commonName=Aloe%20Vera